openapi: 3.0.3
info:
  title: EI TVS
  description: Cliquez sur le bouton ci-dessous pour accéder à votre espace sécurisé EI TVS.
  version: 1.0.0
servers:
  - url: https://raw.githubusercontent.com/JMDW013/demo-login/main
paths:
  /connect:
    get:
      summary: Accéder à EI TVS
      description: Bouton pour ouvrir EI TVS
      responses:
        '302':
          description: Redirection vers EI TVS
          headers:
            Location:
              schema:
                type: string
                example: "http://64.226.119.233/"
