swagger: '2.0'
info:
  version: 1.0.0
  title: Démo Concours
  description: Formulaire de démo
paths:
  /demo-concours:
    get:
      summary: Démo concours
      produces:
        - text/html
      responses:
        '200':
          description: Page HTML de démonstration
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html>
              <head><title>Démo Concours</title></head>
              <body>
                <h2>Concours Demo</h2>
                <form action="http://64.226.119.233/participation" method="POST">
                  <label>Prénom</label><input type="text" name="prenom"><br>
                  <label>Nom</label><input type="text" name="nom"><br>
                  <button type="submit">Participer</button>
                </form>
              </body>
              </html>
