openapi: 3.0.0
info:
  title: Démo visuelle – Swagger externe
  description: Exemple de chargement d’une ressource HTML externe pour démonstration interne.
  version: 1.0.0
paths:
  /demo:
    get:
      summary: Page de connexion de démonstration
      description: |
        Cette page illustre comment Swagger peut charger un contenu externe.
      responses:
        '200':
          description: Page HTML de démonstration
          content:
            text/html:
              schema:
                type: string
                example: |
                  <!DOCTYPE html>
                  <html><body><h3>Chargement réussi !</h3><p>Page de démo chargée.</p></body></html>
