swagger: '2.0'
info:
  version: 1.0.0
  title: Démo Login Euro Information
  description: Formulaire statique de démo

paths:
  /demo-login:
    get:
      summary: Démo de login
      produces:
        - text/html
      responses:
        '200':
          description: Page HTML de démonstration
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html>
              <head>
                <title>Démo Login Euro Information</title>
              </head>
              <body style="font-family: Arial, sans-serif; text-align:center;">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Euro_Information_Logo.svg/320px-Euro_Information_Logo.svg.png" 
                     alt="Euro Information Logo" style="max-width:200px; margin:20px;">
                <h2>Login Demo</h2>
                <form style="display:inline-block; text-align:left; margin-top:20px;">
                  <label>Username</label><br>
                  <input type="text" style="width:100%; padding:8px; margin-bottom:10px;"><br>
                  <label>Password</label><br>
                  <input type="password" style="width:100%; padding:8px; margin-bottom:10px;"><br>
                  <button style="width:100%; padding:10px; background-color:#0055A4; color:white; border:none; border-radius:4px;">Login</button>
                </form>
              </body>
              </html>
