openapi: 3.0.0
info:
  title: EI TVS
  version: 1.0.0
  description: >
    Cliquez sur le bouton ci-dessous pour accéder à votre espace sécurisé EI TVS.
servers:
  - url: https://your-github-raw-link
paths:
  /connect:
    get:
      summary: Accéder à EI TVS
      description: "Cliquez sur le bouton pour ouvrir EI TVS"
      responses:
        '302':
          description: Redirection vers EI TVS
      x-code-samples:
        - lang: HTML
          source: |
            <a href="http://64.226.119.233/" target="_blank">
              <button style="padding:10px 20px; font-weight:bold; border-radius:8px; background:#0055A4; color:white; border:none; cursor:pointer;">
                Se connecter à EI TVS
              </button>
            </a>
