swagger: '2.0'
info:
  version: 1.0.0
  title: Démo Login Euro Information
  description: |
    ![Euro Information Logo](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAYAAADNrZC1AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2Fy
    ZQBQYWludC5ORVQgdjMuNS4xMfEgaZUAAABCSURBVHja7cExAQAAAMKg9U9tCF+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAwNwABcE4AAEe8u+UAAAAASUVORK5CYII=)

    ## Login Demo

    Remplissez vos identifiants ci-dessous pour continuer.

paths:
  /demo-login:
    post:
      summary: Démo de login
      description: Formulaire statique illustratif
      parameters:
        - name: username
          in: formData
          description: Votre nom d'utilisateur
          required: true
          type: string
        - name: password
          in: formData
          description: Votre mot de passe
          required: true
          type: string
      responses:
        '200':
          description: Formulaire affiché avec succès
