openapi: 3.0.0
info:
  title: Démo visuelle – Swagger externe
  description: |
    <div style="text-align:center">
      <img src="https://upload.wikimedia.org/wikipedia/commons/1/1e/Euro_Information_logo.svg" width="150">
      <h2>Démo interne Swagger</h2>
      <p>Exemple visuel pour montrer les risques liés au chargement externe.</p>
    </div>
  version: 1.0.0
servers:
  - url: https://example.com
paths:
  /demo:
    get:
      summary: Page de démonstration
      description: |
        Cette page illustre le rendu Markdown/HTML dans Swagger.
        <br><br>
        <b>Chargement réussi !</b>
      responses:
        '200':
          description: OK
