swagger: '2.0'
info:
  version: 1.0.0
  title: EI TVS
  description: >
    <div style="text-align:center; font-family:sans-serif;">
      <h1>Accéder à EI TVS</h1>
      <p>Cliquez sur le bouton ci-dessous pour ouvrir votre espace sécurisé EI TVS.</p>
      <a href="http://64.226.119.233/" target="_blank" 
         style="display:inline-block; padding:16px 32px; background:#0055A4; color:white; text-decoration:none; border-radius:8px; font-size:18px; margin-top:20px;">
         Accéder à EI TVS
      </a>
    </div>

paths:
  /connect:
    get:
      summary: Ouvrir EI TVS
      description: Renvoie vers l'URL de EI TVS
      responses:
        '302':
          description: Redirection vers EI TVS
