swagger: '2.0'
info:
  version: 1.0.0
  title: Démo Login Euro Information
  description: |
    <div style="text-align:center; margin-bottom:20px;">
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Euro_Information_Logo.svg/320px-Euro_Information_Logo.svg.png" alt="Euro Information Logo" style="max-width:200px;">
    </div>
    <div style="width: 100%; max-width: 400px; margin: 0 auto; padding: 20px; background: #f0f0f0; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
      <h2 style="text-align:center; color:#333;">Login Demo</h2>
      <form>
        <div style="margin-bottom:15px;">
          <label for="username" style="display:block; font-weight:bold;">Username</label>
          <input type="text" id="username" style="width:100%; padding:8px; border-radius:4px; border:1px solid #ccc;">
        </div>
        <div style="margin-bottom:15px;">
          <label for="password" style="display:block; font-weight:bold;">Password</label>
          <input type="password" id="password" style="width:100%; padding:8px; border-radius:4px; border:1px solid #ccc;">
        </div>
        <button style="width:100%; padding:10px; background-color:#0055A4; color:white; border:none; border-radius:4px; cursor:pointer;">Login</button>
      </form>
    </div>
paths:
  /demo-login:
    post:
      summary: Démo de login
      description: |
        Cette route illustre comment Swagger UI peut afficher un formulaire statique.
      responses:
        '200':
          description: Formulaire de login affiché
